version: '1'
services:
  bookingService:
    build:
      context: ./BookingService/
    links:
      - mongo
      - rabbitmq
    ports:
      - "8081:8081"
    command: npm run start
  roomService:
    build:
      context: ./RoomService/
    links:
      - mongo
      - rabbitmq
    ports:
      - "8082:8082"
    command: npm run start
  userService:
    build:
      context: ./UserService/
    links:
      - mongo
      - rabbitmq
    ports:
      - "8083:8083"
    command: npm run start
  mongo:
    image: mongo
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"